### ISSUE TITLE
Can't build YandexMobileAds for iOS

### ISSUE THREAD

**Issue by Lerg** [defold/extender#403] opened 2024-07-12 11:55 UTC
Yandex released a new version of their SDK, plus Defold has been updated so I tried building again with Defold 1.9.1 beta and YandexMobileAds 7.1.1

It still doesn't build but the error message has changed, now it complains about iOS SDK version not being at least 13, however it is set to be so in the Podfile:
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.1.1'
pod 'YandexMobileAdsMediation', '7.1.1'
```

Thee new error:
```
/var/folders/pf/6r_png356xb4lby2dkvym42r0000gn/T/job9582903447976259256/CocoaPodsService/Pods/DivKit/DivKit/Views/DivBlockProvider.swift:77:5: error: concurrency is only available in iOS 13.0.0 or newer
  ) async {
    ^
/var/folders/pf/6r_png356xb4lby2dkvym42r0000gn/T/job9582903447976259256/CocoaPodsService/Pods/DivKit/DivKit/Views/DivBlockProvider.swift:74:8: note: add @available attribute to enclosing instance method
  func setSource(
       ^
```

Full build log
[log.txt.zip](https://github.com/user-attachments/files/16193483/log.txt.zip)

The same result with bob.jar

**Comment by TinyDobbins** [comment] 2024-07-23 14:28
I really hope for a fix for this problem :( here my Podfile with updated version adapters for Yandex 7.2.0:
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.2.0'
pod 'AppLovinYandexMobileAdsAdapters', '12.5.0.2'
pod 'IronSourceYandexMobileAdsAdapters', '8.1.0.2'
pod 'MintegralYandexMobileAdsAdapters', '7.6.7.0'
```

and error logs:
[log.txt](https://github.com/user-attachments/files/16350326/log.txt)

**Comment by britzl** [comment] 2024-08-06 10:42
I'm looking into this again.

> concurrency is only available in iOS 13.0.0 or newer

It seems like we have a hardcoded iOS min version of 11.0. We should override this somehow, possibly based on what is specified in the Podfile, or what individual Podspecs define, or what the user has in Info.plist

**Comment by AGulev** [comment] 2024-08-07 10:50
I think it should work similar way it works on android:
We specify it in `game.project`, it's end up in AndroidManifest.xml, when dependencies resolved it build and if version specified in `game.project` lower that requested by dependencies it throws an error.

**Closed** 2024-09-26 12:36 UTC

**Comment by TinyDobbins** [comment] 2024-09-27 07:59
maybe I'm doing something wrong, but I'm getting this issue during building iOS:
`WARNING: Plist adding value for key 'MinimumOSVersion': '13.0'`

simple project repo case:
[test_yandex.zip](https://github.com/user-attachments/files/17160841/test_yandex.zip)

log file:
[log.txt.zip](https://github.com/user-attachments/files/17160844/log.txt.zip)

build in:
![image](https://github.com/user-attachments/assets/67e64b3e-8dd8-46bc-bc4e-79ed8bff4023)

also attach the podfiles:
works, but very outdated version of YandexMobileAds `6.0.1`:
```
platform :ios, '13.0'
pod 'YandexMobileAds', '6.1.0'
pod 'AppLovinYandexMobileAdsAdapters', '11.11.3.1'
pod 'IronSourceYandexMobileAdsAdapters', '7.5.0.1'
pod 'MintegralYandexMobileAdsAdapters', '7.4.7.0'
```

the next version that does not compile on is YandexMobileAds `6.0.2`: (also in repo case project)
```
platform :ios, '13.0'
pod 'YandexMobileAds', '6.2.0'
pod 'AppLovinYandexMobileAdsAdapters', '11.11.4.0'
pod 'IronSourceYandexMobileAdsAdapters', '7.5.1.0'
pod 'MintegralYandexMobileAdsAdapters', '7.4.7.1'
```

the current version (it would be a magic if it worked) is YandexMobileAds `7.5.1`: 

```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.5.1'
pod 'AppLovinYandexMobileAdsAdapters', '12.6.1.2'
pod 'IronSourceYandexMobileAdsAdapters', '8.3.0.2'
pod 'MintegralYandexMobileAdsAdapters', '7.6.9.3'
```

**Comment by britzl** [comment] 2024-09-27 08:15
Are you using a local extender and not the official one? The above fix has not been released yet.

**Comment by TinyDobbins** [comment] 2024-09-27 08:19
oh, I saw the issue is “closed,” so I thought I'd test it. 
I use only official  `build.defold.com` and `build-stage.defold.com` servers.

**Comment by britzl** [comment] 2024-09-30 09:31
> oh, I saw the issue is “closed,” so I thought I'd test it. I use only official `build.defold.com` and `build-stage.defold.com` servers.
I understand. But the duplicate `PrivacyInfo.xcprivacy` is new.

**Comment by TinyDobbins** [comment] 2024-10-17 07:49
@britzl thanks a lot for this fix!

for all other users of this extension:
it is now possible to use a fresh version YandexMobileAds 7.3.0 ! 
```
platform :ios, '13.0'
pod 'YandexMobileAds', '7.3.0'
pod 'YandexMobileAdsAdMobAdapters'
pod 'AppLovinYandexMobileAdsAdapters'
pod 'IronSourceYandexMobileAdsAdapters'
pod 'MintegralYandexMobileAdsAdapters'
```

**Comment by osov** [comment] 2024-12-13 10:27
Defold 1.9.5 not building IOS
[ext.manifest](https://github.com/osov/defold-yandex-easy-monetization/blob/main/extension-yandex-ads/ext.manifest)
[podfile](https://github.com/osov/defold-yandex-easy-monetization/blob/main/extension-yandex-ads/manifests/ios/Podfile)
[log.zip](https://github.com/user-attachments/files/18124904/log.zip)

**Comment by AGulev** [comment] 2024-12-13 16:30
this is old closed issue
if you have a new problem - open a new issue
