### ISSUE TITLE
iOS build stopped working

### ISSUE THREAD

**Issue by osov** [defold/extender#357] opened 2024-02-20 12:54 UTC
Just yesterday the assembly for iOS was working, today I get an error.
com.defold.extender.ExtenderException: java.io.IOException:   Preparing

My extension:
https://github.com/osov/defold-yandex-easy-monetization/archive/refs/heads/main.zip

**Defold version (REQUIRED):**
  - Version 1.6.4

**Platforms (REQUIRED):**
 - Platforms:  macOS

[log (2).txt](https://github.com/defold/defold/files/14344528/log.2.txt)

**Comment by osov** [comment] 2024-04-09 08:03
The problem is relevant, there was simply no way to fully check it. According to the error logs, it cannot load the file. But if you open this link in a browser, everything is displayed (the file exists).
[log (5).txt](https://github.com/defold/extender/files/14915398/log.5.txt)

**Comment by dri-richard** [comment] 2024-04-23 14:58
Can/should we continue using the temp build server with 1.8.0? i.e. is it valid for testing the beta and then using in production?

**Comment by JCash** [comment] 2024-04-23 15:12
The beta server is always recommended when using the Defold Beta (which it currently is).
Tomorrow, we'll release Defold 1.8.0 Stabel version, and it'll use the live build server (which is already live at build.defold.com)

**Comment by britzl** [comment] 2024-04-24 08:38
@dri-richard and @osov I've manually wiped the cocoapod cache (Library/Caches/Cocoapods) and repos (.cocoapods/repos) and was now able to successfully build the project in the original post! Not sure if we'll run into CDN issues again, but please give it a try and let me know how it goes.

**Comment by britzl** [comment] 2024-04-24 21:33
To clarify: Please use the standard build.defold.com and build-stage.defold.com and not the experimental server.

**Comment by britzl** [comment] 2024-04-29 06:22
I'm closing this as I believe it to be fixed now. Please re-open if that is not the case.

**Closed by britzl** 2024-04-29 06:22 UTC
Labels: bug

**Comment by dri-richard** [comment] 2024-04-29 08:46
We switched back to build.defold.com and it seems fine, but we don't build for iOS as frequently as we do Android due to the higher Github Actions cost.

**Comment by Shocopop** [comment] 2024-08-09 14:19
Hey, the problem is happening again, it has started yesterday.
[log.txt](https://github.com/user-attachments/files/16562374/log.txt)
